### ISSUE TITLE
[BUG] NBT strings don't work.

### ISSUE THREAD

**Issue by HollyAssasin** [JT122406/HungerGames#10]
**Describe the bug**

Tried adding some custom items using CustomDataModel and NBT strings, yet did not work,

**To Reproduce**

- DIAMOND_SWORD 1 data:{Unbreakable:1b,display:{Name:'{"text":"Bob\'s_Sword"}'},Damage:500}
Add this from the wiki to the chest loot config, it will be a normal sword.

**Expected behavior**

Sword with enchantments and name.

**Screenshots/Errors**

**Version Info:**
 - **Plugin Version:** 5.1.1
 - **Server Version/Platform** Paper 1.19.2

**Comment by JT122406** [comment]
Yes this is a Known issue I am working on Since I moved the project from Maven to Gradle I am still working on all the shading

**Comment by HollyAssasin** [comment]
Was the issue fixed in the latest update? The Sword still does not work.

**Comment by JT122406** [comment]
It should be

**Comment by HollyAssasin** [comment]
Tested it yesterday and the sword example still does not work.

**Comment by HollyAssasin** [comment]
Closed by accident

**Comment by HollyAssasin** [comment]
I closed this from mobile by mistake, I apologize. But the Bob sword example still does not work in 5.2.0

**Comment by JT122406** [comment]
try installing NBTAPI plugin on server

**Comment by HollyAssasin** [comment]
Just installed NBTAPI and tested it, yet nothing changed. 
`DIAMOND_SWORD 1 data:{Unbreakable:1b,display:{Name:'{"text":"Bob's_Sword"}'},Damage:500}` does not work.
Also, the `/hg nbt` command does not work.

**Comment by JT122406** [comment]
Lovely

**Comment by JT122406** [comment]
I released a build in my discord with a fix
