### ISSUE TITLE
[BUG] clicking sign does not work if you are on bedrock

### ISSUE THREAD

**Issue by Yomamaeatstoes** [JT122406/HungerGames#12]
**Describe the bug**
 The sign does not work when you click on it on bedrock

**To Reproduce**
 go to bedrock and click on the sign

**Expected behavior**
 you should be able to click on the sign and join

**Screenshots/Errors**
 basically, a screenshot of the signs

**Version Info:**
 - **Plugin Version:**   5.2.0
 - **Server Version/Platform**  paper 1.19.2

**Additional context**

**Comment by JT122406** [comment]
This is an issue with Geyser set up

**Comment by JT122406** [comment]
nothing can be done on plugin side
