### ISSUE TITLE
[BUG] Critical The Gui does not work for bedrock players. The leave icon specifically does not work for bedrock players.

### ISSUE THREAD

**Issue by Yomamaeatstoes** [JT122406/HungerGames#14]
**Describe the bug**
  The leave gui does not work when clicking on it on bedrock

**To Reproduce**
 Click on the leave button in the game on bedrock

**Expected behavior**
 You should be able to click on the button and leave on bedrock

**Screenshots/Errors**

**Version Info:**
 - **Plugin Version:**  5.2.0
 - **Server Version/Platform** 1.19.2

**Additional context**

**Comment by JT122406** [comment]
Like the nether star doesn't work when using geyser?

**Comment by JT122406** [comment]
This is an issue with Geyser set up

nothing can be done on plugin side

**Comment by Yomamaeatstoes** [comment]
Thanks for responding! I have another bug with an error report in my console. Look at github. #21
