### ISSUE TITLE
[BUG] Kit items are cleared on match start

### ISSUE THREAD

**Issue by datatags** [JT122406/HungerGames#2]
**Describe the bug**
Players' kit items are cleared when the match starts

**To Reproduce**
1. Join a match
2. Pick a kit
3. Wait for the match to start
4. See all your items disappear

**Expected behavior**
Players to keep their kit items

**Screenshots/Errors**
No errors, and I think it's pretty self-explanatory

**Version Info:**
 - **Plugin Version:** 5.0.1
 - **Server Version/Platform** Paper 1.18.2: `This server is running Paper version git-Paper-324 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT) (Git: 8c9d98e)`

**Additional context**
Not that I know of

**Comment by craftermcnet** [comment]
Same issue, but happens also without choosing a kit.

**Comment by JT122406** [comment]
Having more issues than I expected 
sorry for the wait
