### ISSUE TITLE
[BUG] Players can move before game starts

### ISSUE THREAD

**Issue by tristanpoland** [JT122406/HungerGames#24]
**Describe the bug**

When the players are waiting in the arena spamming jump and w allows for movement

**To Reproduce**

Join a game and spam w and spacebar while the game counts down

**Expected behavior**

Player should be unable to move

**Version Info:**
 - **Plugin Version:** 5.2.3
 - **Server Version/Platform** Paper 1.19.3

**Comment by sovtec** [comment]
Same problem

**Comment by JT122406** [comment]
full movement or just jumping?
