### ISSUE TITLE
paper-1.19

### ISSUE THREAD

**Issue by NEIKI19914** [JT122406/HungerGames#6]
The champion sometimes has no reward items, if entering the match with a prop, the prop will disappear at the end of the match, and full players can not automatically start the match.
paper-1.19-experimental-6.jar HungerGames-5.0.5

**Comment by JT122406** [comment]
This is fixed in my latest commit will push update soon

**Comment by NEIKI19914** [comment]
Thank you very much, my players are looking forward to it all the time, there is a small problem, joining the game in other dimensions will cause the inventory to disappear, is this also solved?



> This is fixed in my latest commit will push update soon

**Comment by JT122406** [comment]
> Thank you very much, my players are looking forward to it all the time, there is a small problem, joining the game in other dimensions will cause the inventory to disappear, is this also solved?
> 
> > This is fixed in my latest commit will push update soon

that is certainly interesting so um probably not lol

**Comment by NEIKI19914** [comment]
> > Thank you very much, my players are looking forward to it all the time, there is a small problem, joining the game in other dimensions will cause the inventory to disappear, is this also solved?
> > > This is fixed in my latest commit will push update soon
> 
> that is certainly interesting so um probably not lol

Thank you very much
