### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Wuemeli** [JT122406/HungerGames#9]
Keeps spamming in my console:
31.07 16:10:47 [Server] ERROR Unhandled exception number 4096 occured in onPacketSending(PacketEvent) for eco
31.07 16:10:47 [Server] INFO java.lang.NoSuchMethodError: 'com.comphenix.protocol.reflect.StructureModifier com.comphenix.protocol.reflect.StructureModifier.modify(int, java.util.function.UnaryOperator)'
31.07 16:10:47 [Server] INFO at com.willfp.eco.internal.spigot.display.PacketSetSlot.onSend(PacketSetSlot.kt:20) ~[eco-6.38.2-all.jar:?]
31.07 16:10:47 [Server] INFO at com.willfp.eco.core.AbstractPacketAdapter.onPacketSending(AbstractPacketAdapter.java:119) ~[eco-6.38.2-all.jar:?]
31.07 16:10:47 [Server] INFO at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195) ~[ProtocolLib.jar:?]
31.07 16:10:47 [Server] INFO at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149) ~[ProtocolLib.jar:?]
31.07 16:10:47 [Server] INFO at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:535) ~[ProtocolLib.jar:?]
31.07 16:10:47 [Server] INFO at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:516) ~[ProtocolLib.jar:?]
31.07 16:10:47 [Server] INFO at com.comphenix.protocol.injector.netty.ProtocolInjector.packetQueued(ProtocolInjector.java:346) ~[ProtocolLib.jar:?]
31.07 16:10:47 [Server] INFO at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketSending(ProtocolInjector.java:308) ~[ProtocolLib.jar:?]
31.07 16:10:47 [Server] INFO at com.comphenix.protocol.injector.netty.ChannelInjector.processSending(ChannelInjector.java:436) ~[ProtocolLib.jar:?]
31.07 16:10:47 [Server] INFO at com.comphenix.protocol.injector.netty.ChannelInjector.access$800(ChannelInjector.java:72) ~[ProtocolLib.jar:?]
31.07 16:10:47 [Server] INFO at com.comphenix.protocol.injector.netty.ChannelInjector$3.handleScheduled(ChannelInjector.java:376) ~[ProtocolLib.jar:?]
31.07 16:10:47 [Server] INFO at com.comphenix.protocol.injector.netty.ChannelInjector$3.onMessageScheduled(ChannelInjector.java:346) ~[ProtocolLib.jar:?]
31.07 16:10:47 [Server] INFO at com.comphenix.protocol.injector.netty.ChannelProxy$2.schedulingRunnable(ChannelProxy.java:127) ~[ProtocolLib.jar:?]
31.07 16:10:47 [Server] INFO at com.comphenix.protocol.injector.netty.EventLoopProxy.execute(EventLoopProxy.java:95) ~[ProtocolLib.jar:?]
31.07 16:10:47 [Server] INFO at net.minecraft.network.Connection.writePacket(Connection.java:435) ~[?:?]
31.07 16:10:47 [Server] INFO at net.minecraft.network.Connection.send(Connection.java:382) ~[?:?]
31.07 16:10:47 [Server] INFO at net.minecraft.server.network.ServerGamePacketListenerImpl.send(ServerGamePacketListenerImpl.java:2123) ~[?:?]
31.07 16:10:47 [Server] INFO at net.minecraft.server.network.ServerGamePacketListenerImpl.send(ServerGamePacketListenerImpl.java:2109) ~[?:?]
31.07 16:10:47 [Server] INFO at org.bukkit.craftbukkit.v1_18_R2.inventory.CraftInventoryPlayer.setItem(CraftInventoryPlayer.java:113) ~[purpur-1.18.2.jar:git-Purpur-1632]
31.07 16:10:47 [Server] INFO at org.bukkit.craftbukkit.v1_18_R2.inventory.CraftInventory.clear(CraftInventory.java:442) ~[purpur-1.18.2.jar:git-Purpur-1632]
31.07 16:10:47 [Server] INFO at org.bukkit.craftbukkit.v1_18_R2.inventory.CraftInventory.clear(CraftInventory.java:448) ~[purpur-1.18.2.jar:git-Purpur-1632]
31.07 16:10:47 [Server] INFO at tk.shanebee.hg.util.Util.clearInv(Util.java:226) ~[HungerGames-5.1.1.jar:?]
31.07 16:10:47 [Server] INFO at tk.shanebee.hg.data.PlayerData.<init>(PlayerData.java:61) ~[HungerGames-5.1.1.jar:?]
31.07 16:10:47 [Server] INFO at tk.shanebee.hg.game.GamePlayerData.lambda$join$1(GamePlayerData.java:290) ~[HungerGames-5.1.1.jar:?]
31.07 16:10:47 [Server] INFO at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) ~[?:?]
31.07 16:10:47 [Server] INFO at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) ~[?:?]
31.07 16:10:47 [Server] INFO at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2147) ~[?:?]
31.07 16:10:47 [Server] INFO at org.bukkit.craftbukkit.v1_18_R2.entity.CraftEntity.lambda$teleportAsync$0(CraftEntity.java:547) ~[purpur-1.18.2.jar:git-Purpur-1632]
31.07 16:10:47 [Server] INFO at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.18.2.jar:git-Purpur-1632]
31.07 16:10:47 [Server] INFO at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
31.07 16:10:47 [Server] INFO at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
31.07 16:10:47 [Server] INFO at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1427) ~[purpur-1.18.2.jar:git-Purpur-1632]
31.07 16:10:47 [Server] INFO at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:188) ~[purpur-1.18.2.jar:git-Purpur-1632]
31.07 16:10:47 [Server] INFO at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
31.07 16:10:47 [Server] INFO at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1404) ~[purpur-1.18.2.jar:git-Purpur-1632]
31.07 16:10:47 [Server] INFO at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1397) ~[purpur-1.18.2.jar:git-Purpur-1632]
31.07 16:10:47 [Server] INFO at net.minecraft.util.thread.BlockableEventLoop.runAllTasks(BlockableEventLoop.java:114) ~[?:?]
31.07 16:10:47 [Server] INFO at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1531) ~[purpur-1.18.2.jar:git-Purpur-1632]
31.07 16:10:47 [Server] INFO at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1247) ~[purpur-1.18.2.jar:git-Purpur-1632]
31.07 16:10:47 [Server] INFO at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:321) ~[purpur-1.18.2.jar:git-Purpur-1632]

**Comment by JT122406** [comment]
When does this happen?

**Comment by Wuemeli** [comment]
Random
